### ISSUE TITLE
JS Interop issue in handlebars2.dart in gitlab pipeline

### ISSUE THREAD

**Issue by tejaswi-gayathri** [zyzbroker/HandlebarDart#1]
Hi,

Could you please help me with this issue:
I am using **handlebars2** dependency in my angular dart project. It was working fine for long time. Recently when I had to push the code to gitlab I get the following error during build phase and pipeline fails:

![gitlabissue](https://user-images.githubusercontent.com/17849425/90616938-b6689600-e22b-11ea-96cd-09ee6515b9cd.png)

Current version of handlebars being used in pubspec.yaml file is:
handlebars2: ^0.0.3

**Comment by zeljkokunica** [comment]
This will help: https://github.com/zyzbroker/HandlebarDart/pull/2

**Comment by david-onehub-dev** [comment]
externalize those fakecontructor fix the build issue. It is tested on sdk 2.10.1

**Comment by zyzbroker** [comment]
We have externalized those constructor. and package is released
