### ISSUE TITLE
Question - Could you use this to update the header meta tags

### ISSUE THREAD

**Issue by isAlmogK** [zyzbroker/HandlebarDart#3]
Wounder if it would be possible to update the header meta tags?

**Comment by zyzbroker** [comment]
It does not prevent you from compiling "<head><title>{{title}}</title><meta name="description" value="{{desription}}" /></head>". But you have to find some way to insert the resolved content into it. 

You can reference to the handlerBar js docuemnt and as far how to do it. you can reference svelte.js <svelte:head>. here is the link https://svelte.dev/docs#svelte_head

You can reference to javascript-the definite guide
